name: Build and Test Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test application locally
      run: |
        python main.py --url https://github.com/test --output test_qr.png
        ls -la qr_codes/
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-qr-code
        path: qr_codes/test_qr.png

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t qr-code-generator-app .
    
    - name: Test Docker container
      run: |
        # Run container and wait for completion
        docker run --name test-container qr-code-generator-app --url https://github.com/actions-test
        
        # Copy QR code from container
        docker cp test-container:/app/qr_codes ./docker-qr-codes
        
        # Verify QR code was created
        ls -la docker-qr-codes/
        
        # Check container logs
        docker logs test-container
    
    - name: Upload Docker test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docker-qr-code
        path: docker-qr-codes/
    
    - name: Clean up
      run: |
        docker rm test-container

  docker-push:
    runs-on: ubuntu-latest
    needs: [test, docker-build]
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'AndyLanchipa'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/qr-code-generator-app:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/qr-code-generator-app:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
